# Generated by Django 5.1.4 on 2024-12-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Patient ID')),
                ('student_employee_id', models.IntegerField(null=True, unique=True, verbose_name='Student Employee ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('address_lot_no', models.CharField(max_length=50, null=True, verbose_name='Address Lot Number')),
                ('address_street', models.CharField(max_length=50, null=True, verbose_name='Address Street Number')),
                ('address_barangay', models.CharField(max_length=50, null=True, verbose_name='Address Barangay')),
                ('address_municipality', models.CharField(max_length=50, null=True, verbose_name='Address Municipality')),
                ('address_province', models.CharField(max_length=50, null=True, verbose_name='Address Province')),
                ('campus', models.CharField(max_length=100, verbose_name='Campus')),
                ('college_office', models.CharField(choices=[('College of Architecture and Fine Arts (CAFA)', 'College of Architecture and Fine Arts (CAFA)'), ('College of Arts and Letters (CAL)', 'College of Arts and Letters (CAL)'), ('College of Business Education and Accountancy (CBEA)', 'College of Business Education and Accountancy (CBEA)'), ('College of Criminal Justice Education (CCJE)', 'College of Criminal Justice Education (CCJE)'), ('College of Hospitality and Tourism Management (CHTM)', 'College of Hospitality and Tourism Management (CHTM)'), ('College of Information and Communications Technology (CICT)', 'College of Information and Communications Technology (CICT)'), ('College of Industrial Technology (CIT)', 'College of Industrial Technology (CIT)'), ('College of Law (CLaw)', 'College of Law (CLaw)'), ('College of Nursing (CN)', 'College of Nursing (CN)'), ('College of Engineering (COE)', 'College of Engineering (COE)'), ('College of Education (COED)', 'College of Education (COED)'), ('College of Science (CS)', 'College of Science (CS)'), ('College of Sports, Exercise and Recreation (CSER)', 'College of Sports, Exercise and Recreation (CSER)'), ('College of Social Sciences and Philosophy (CSSP)', 'College of Social Sciences and Philosophy (CSSP)'), ('Graduate School (GS)', 'Graduate School (GS)')], max_length=100, null=True, verbose_name='College/Office')),
                ('course_year_section', models.CharField(max_length=100, verbose_name='Course/Year/Section')),
                ('emergency_contact', models.CharField(max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_number', models.CharField(max_length=15, verbose_name='Emergency Contact Number')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('patient_role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Non-Academic Personnel', 'Non-Academic Personnel')], max_length=25, null=True)),
                ('priority_type', models.CharField(choices=[('PWD', 'PWD'), ('Senior', 'Senior'), ('Personnel', 'Personnel'), ('Regular', 'Regular')], max_length=10, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('allergies', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Appointment ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Certificates', 'Certificates'), ('Others', 'Others')], max_length=50)),
                ('ticket_type', models.CharField(choices=[('Appointment', 'Appointment'), ('Walk-in', 'Walkin')], max_length=50, null=True)),
                ('queue_type', models.CharField(choices=[('Priority', 'Priority'), ('Regular', 'Regular')], max_length=20)),
                ('queue_status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('queue_category', models.CharField(choices=[('Absence Certificate', 'Absence Certificate'), ('Employment Certificate', 'Employment Certificate'), ('OJT Certificate', 'OJT Certificate'), ('OSRA Certificate', 'OSRA Certificate')], max_length=40, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Nurse', 'Nurse'), ('Dentist', 'Dentist'), ('Physician', 'Physician')], max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.admin')),
            ],
        ),
    ]
