# Generated by Django 5.1.4 on 2024-12-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='certificate_category',
            field=models.CharField(choices=[('Absence Certificate', 'Absence Certificate'), ('Employment Certificate', 'Employment Certificate'), ('OJT Certificate', 'OJT Certificate'), ('OSRA Certificate', 'OSRA Certificate')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='queue_category',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Dental', 'Dental')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_diagnosis', models.DateField()),
                ('initial_diagnosis', models.TextField()),
                ('attending_staff', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('assessment', models.TextField()),
                ('prescription', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
    ]
