# Generated by Django 5.1.4 on 2024-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_admin_contact_number_remove_admin_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profile_pics/'),
        ),
    ]
