# Generated by Django 5.1.4 on 2024-12-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_admin_contact_number_admin_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(default='Super Admin', max_length=50),
        ),
    ]
