# Generated by Django 5.1.4 on 2024-12-23 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_staff_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_active',
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
