# Generated by Django 5.1.4 on 2024-12-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_staff_is_active_staff_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='Is Logged In'),
        ),
    ]
